"""Public API surface for Flowinone file handling."""

from .fs_media import (
    get_all_folders_info,
    get_folder_images,
    get_video_details,
    get_image_details,
    has_db_main,
)
from .models import (
    AccessDenied,
    BookmarkError,
    BookmarkNotFound,
    ExternalServiceError,
    FolderNotFound,
    MediaDetail,
    MediaEntry,
    MediaError,
    MediaNotFound,
    PageMetadata,
)
from .chrome_bookmarks import (
    get_chrome_bookmarks,
    get_chrome_youtube_bookmarks,
    has_chrome_bookmarks,
)
from .eagle_integration import (
    is_eagle_available,
    get_eagle_folders,
    get_eagle_images_by_folderid,
    get_eagle_images_by_tag,
    get_eagle_tags,
    search_eagle_items,
    get_eagle_stream_items,
    get_eagle_video_details,
    get_eagle_image_details,
    get_subfolders_info,
)
from .item_db import (
    iter_tagged_items,
    update_item_database,
    update_missing_thumbnails,
    fetch_items,
    clear_thumbnails,
)

__all__ = [
    "get_all_folders_info",
    "get_folder_images",
    "get_video_details",
    "get_image_details",
    "iter_tagged_items",
    "update_item_database",
    "update_missing_thumbnails",
    "fetch_items",
    "clear_thumbnails",
    "has_db_main",
    "AccessDenied",
    "BookmarkError",
    "BookmarkNotFound",
    "ExternalServiceError",
    "FolderNotFound",
    "MediaDetail",
    "MediaEntry",
    "MediaError",
    "MediaNotFound",
    "PageMetadata",
    "get_chrome_bookmarks",
    "get_chrome_youtube_bookmarks",
    "has_chrome_bookmarks",
    "is_eagle_available",
    "get_eagle_folders",
    "get_eagle_images_by_folderid",
    "get_eagle_images_by_tag",
    "get_eagle_tags",
    "search_eagle_items",
    "get_eagle_stream_items",
    "get_eagle_video_details",
    "get_eagle_image_details",
    "get_subfolders_info",
]
